version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
      - "./logs:/app/logs"
    expose:
      - "5000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    volumes:
      - .:/app
    ports:
      - "1080:80"
    depends_on:
      - flask
    restart: unless-stopped

  db:
    image: mysql
    command: --init-file /init-app/init.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: pyerp
    volumes:
      - "./app/db-init/init.sql:/init-app/init.sql"
    restart: unless-stopped
